name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,docs]
      - name: Lint
        run: |
          ruff check .
          ruff format --check .
      - name: Mypy
        run: mypy sentrykit
      - name: Tests
        run: pytest
      - name: Build docs
        run: mkdocs build
